### ISSUE TITLE
VIP list inactive on the cache "Zidovsky cintorin v Beckove"

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#112]
I've just come across a cache page that breaks GClh II. :-) It is [Zidovsky cintorin v Beckove](https://www.geocaching.com/geocache/GC54C3Y_zidovsky-cintorin-v-beckove).

Don't know what is happening here but the VIP list and the entire right column gets un-clickable while the cursor turns into a hand symbol as if it is above a link. But when clicked it does not load any page. Try it yourself.

**Comment by 2Abendsegler** [comment]
Hi,

really a dubious effekt! 
But please try it without GClh II. You will see the effect is the same.
 
It comes from the cache description area. There are used jquery elements (fancybox) which should not be used in a cache description. With this elements, the owner can change the right area in the screen. Please look to the picture.

I will not do anything against that. I mean, it is the task of Groundspeak to lock in the cache description so it can not do anything outside the cache desription area. This is called sandbox, I mean.

So, if this cache would be in my area, I would call the owner, to remove this elements from the description. If he do nothing, I would call the reviewer [Vrso](https://www.geocaching.com/profile/?guid=f65fcb31-4fce-4505-a3e6-1a7a09b850c5) with the request to let it change.

If this description is ok, please close the issue. Otherwise please come back.
Regards
![fancybox in cache description](https://cloud.githubusercontent.com/assets/22332216/22553162/0266d570-e95c-11e6-9bbe-1db4e252537b.jpg)

**Comment by PontiacCZ** [comment]
Oh, I see, you're right, it's in the page code. I'm sorry, I should have tried with GM off first. Closing this issue. :)
