### ISSUE TITLE
Cache listing page is very slow.

### ISSUE THREAD

**Issue by anvanlaer** [2Abendsegler/GClh#1358]
Hi

Running GC little helper makes the sites slow.  The personal notes aren't getting saved.  It keeps saying it is saving.  I cannot correct coordinates.  Well i can put in the adjusted coords but when i submit they won't change.
When i disable GC Little helper then i can use the site just fine.

I am using Chrome on a Windows computer.

Is there something wrong with my settings or is this a bug?

**Comment by 2Abendsegler** [comment]
Hi,

it is nothing wrong with your settings and it seems to be no bug.

We know about this effect, but we don't have a solution at the moment. It only seems to be the case during Seattle work hours, for a few days. And it is only on the cache listing page. In the morning after german time, everything runs smoothly. It is possible that Groundspeak analysis tools are running that are disrupted by the GClh.

Thanks for the message. Please be patient. 

Cheers.

---
@Ruko2010, @capoaira ...
Does anyone have an idea?

**Comment by anvanlaer** [comment]
Ah thanks for confirming it is not something on my end.

I love all the work you guys put into this.

**Comment by 2Abendsegler** [comment]
#1360 Other issue, same problem.

**Comment by 2Abendsegler** [comment]
We now know the problem. 

To set a cache in the cache listing as favorite is no longer possible in the moment. But the GClh expects and needs this possibility. Therefore, some features such as correcting the coordinates or the  construction of the VIPs are disturbed and the display of the cache listing is very slow.

We have opened a [bug report](https://forums.geocaching.com/GC/index.php?/topic/356860-bug-to-set-a-cache-in-the-cache-listing-as-favorite-is-no-longer-possible/).

We are also trying to change the GClh so that the problems no longer arise.

**Comment by 2Abendsegler** [comment]
You can install a pre-release with this [link](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js).
You come back to the original with this [link](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).

We will release a new official version tomorrow at the latest.

**Comment by anvanlaer** [comment]
thanks, i'll install immediatly ;)
