### ISSUE TITLE
"Submit" corrected coordinates does not react

### ISSUE THREAD

**Issue by allyourcodearebelongtous** [2Abendsegler/GClh#1360]
When changing coordinates of a geocache nothing happens after clicking on "Submit".

**To Reproduce**

1. Click on the coordinates of a geocache
2. Enter new coordinates
3. Click on "Submit"
4. Nothing happens

**Expected behavior**
After clicking "Submit" the buttons "Accept" and "Cancel" should appear.

**Screenshots**
![1](https://user-images.githubusercontent.com/46929603/83942111-1042ed80-a7f1-11ea-9289-e74e9cd85ebe.png)
![2](https://user-images.githubusercontent.com/46929603/83942115-12a54780-a7f1-11ea-92da-48c0cc3d7609.png)

Following does only appear when GC little helper is deactivated:
![3](https://user-images.githubusercontent.com/46929603/83942118-146f0b00-a7f1-11ea-80b1-54abf949cb1c.png)

**Desktop (please complete the following information):**
Google Chrome Version 83.0.4103.97 
GC little helper version  0.10.6

**Comment by 2Abendsegler** [comment]
Hi,

we know about this effect, but we don't have a solution at the moment. Since yesterday, it only seems to be the case during Seattle work hours, for a few days. And it is only on the cache listing page. In the morning after german time, everything runs smoothly. It is possible that Groundspeak analysis tools are running that are disrupted by the GClh.

Thanks for the message. Please be patient. We are analysing the effect and try to find a solution.

Cheers.

---
#1358 Other issue, same problem.

**Comment by 2Abendsegler** [comment]
We now know the problem. 

To set a cache in the cache listing as favorite is no longer possible in the moment. But the GClh expects and needs this possibility. Therefore, some features such as correcting the coordinates or the  construction of the VIPs are disturbed and the display of the cache listing is very slow.

We have opened a [bug report](https://forums.geocaching.com/GC/index.php?/topic/356860-bug-to-set-a-cache-in-the-cache-listing-as-favorite-is-no-longer-possible/).

We are also trying to change the GClh so that the problems no longer arise.

**Comment by 2Abendsegler** [comment]
You can install a pre-release with this [link](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js).
You come back to the original with this [link](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).

We will release a new official version tomorrow at the latest.
