### ISSUE TITLE
[New Map] Additional cache information in detail screen of a cache doesn't work.

### ISSUE THREAD

**Issue by olilesp** [2Abendsegler/GClh#1489]
Hello,
I hope you will understand the translation, I am a native French speaker.

When I am on the map, the first selection of a cache does not give any information (logs, latests logs, location and coordinates).
If I select another map, this information appears but it is the information from the first selected cache.
A new selection and I have either the information of the previous cache or no information if i select another cache than previous... 
Noted this bug since the last update
![Capture d’écran 2020-11-06 174222](https://user-images.githubusercontent.com/35106228/98392424-46aebe00-2058-11eb-843b-845c62f2b218.jpg) I choose one cache (Cache #9) . Nothing appears
![Capture d’écran 2020-11-06 174300](https://user-images.githubusercontent.com/35106228/98392427-47475480-2058-11eb-895d-db0085f737d3.jpg) Another cache (cache #8) , there's informations about the previous cache #9 
![Capture d’écran 2020-11-06 174419](https://user-images.githubusercontent.com/35106228/98392430-47dfeb00-2058-11eb-8e54-d7e44a27bc8a.jpg) Returning to Cac he #9, get infos of Cache #8

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug.

The new map (Search Map) is currently being revised, which is why some GClh features no longer work or no longer work correctly. The work is still in progress, so we have to be patient a little longer.
[Release Notes (Website: Progressive release, Search map code refactor) - October 26, 2020](https://forums.geocaching.com/GC/index.php?/topic/359138-release-notes-website-progressive-release-search-map-code-refactor-october-26-2020/)

We observe the status of the work. When the work is done, we will start to make the necessary adjustments in the GClh.

Have a nice Weekend
Frank

**Comment by 2Abendsegler** [comment]
It appears that the changes to the site are complete. Maybe we can start with our adjustments.
Volunteers? 😊

**Comment by Ruko2010** [comment]
I'll have a look into this.

**Comment by capoaira** [comment]
I think it's because the mutation observer doesn't fire when something changes in the sidebar. This is probably the problem for the other bugs in the cache details.
If you load the first cache, you can see the bug described above. If you then move the map, everything works as before.

**Comment by Ruko2010** [comment]
Fixed with #1499
