### ISSUE TITLE
[Global] Audience/Demo mode

### ISSUE THREAD

**Issue by janborup** [2Abendsegler/GClh#1625]
Hi GC-LH coders

**I would like a Audience/Demo-mode option**
Several times I try to learn other GeoCachers about very nice tools to help solving geocaches, and try to learn them using this nice GC-LitteleHelper tool at events and other online screen sharing meetings. 

But there is one big issue - I spoil ALL my corrected coordinates and personalnotes I have on all caches.

**Audience Off/On option in Config**
There should be an easy On/Off (Default:Off) option, to enable this Audience mode.
This should remove all my corrected coordinates and personalnotes from cache-listing.

**Additional options**
There could be support other On/Off blocks in Audience-mode.
- Show VIP/VUP
- Map Show all caches as Not logged.
- Don't Show corrected coords  icon on cache-listing and Corrected-Icon on Map.
 
I can help you coding with this just say, but I might need help with the config configuration about this.

/Cheers

**Comment by Ruko2010** [comment]
Hello @janborup 
Thanks for your input. I think this is a feature, that will not be used by many people.
I think the easier option for you should be to create your own userscript and just hide all elements via css. Such a userscript can be easily enabled/disabled by the tampermonkey menue, so you have an easy on/off switch.
If this is an option for you, we can sure help you with the initial creation of the script, so you just have to add your CSS.

@2Abendsegler / @capoaira  What do you think? Is my answer also representing your opinion or do you think implementing such a feature in GClh II makes sense?

**Comment by 2Abendsegler** [comment]
I could have used such a feature. Especially if you want to show something quickly without any preparation time.

On the other hand, this is certainly a lot of work because especially the coordinates are used in so many places. For example, with external maps and route services such as Flopp's Map, BRouter, GPSVisualizer, Openrouteservice and also with Copy data to Cliboard. And that applies not only to the cache listing, but also, for example, to the popup and the additional data on the maps.

In addition, the GClh is probably not fast enough to really hide the coordinates and the personal cache note. It is more likely that you will see the data briefly and only then will the GClh hide it.

Ultimately, Ruko2010 is certainly right, that this feature will not be used by many people. And that should be the reason, we shouldn't implement this feature.

Jan, perhaps you can work around the problem by selecting a few caches beforehand without corrected coordinates and a personal cache note. You have to prepare for that, but it should work and it doesn't take long. This is my way. And if I do get a cache with corrected coordinates, I quickly reverse it, look for something else and explain it. Everyone understands that too. 

Summary: We shouldn't implement this feature.

**Comment by janborup** [comment]
Thanks very much for your input guys.

I can see this can become performance issues in GC-lh so I'm just glad you can pinpoint the issues in my feature request.

I will try make a small GC-lc2 AddIns script, and try find out the essentials for the DOM changes for the script to fit this feature.

If you have good beginners guide to create a template for GC, please supply me a link.

Thanks from Denmark.

**Comment by Ruko2010** [comment]
This is a simple start for a userscript. You can use it to inject your CSS Styles:

```
// ==UserScript==
// @name         New Userscript
// @namespace    YOUR NAMESPACE
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      https://www.geocaching.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    // CSS Style hinzufügen.
    function appendCssStyle(css, name) {
        var tag;

        if (css == "") return;
        if (name) tag = document.getElementsByTagName(name)[0];
        else tag = document.getElementsByTagName('head')[0];
        var style = document.createElement('style');
        style.innerHTML = 'GClhII{} ' + css;
        style.type = 'text/css';
        tag.appendChild(style);
    }

    alert("I'm alive: Making the Header-Background Blue");
    var css = "nav .wrapper{background-color: blue}";
    appendCssStyle(css);
})();
```

**Comment by 2Abendsegler** [comment]
... or you can use this little ad blocker script, to get started.
https://github.com/2Abendsegler/GC_ad_blocker/blob/master/gc_ad_blocker.user.js

---
A new script doesn't really make your task any easier. And the new script and the GClh script will possibly hinder each other.

If you haven't had a lot of experience developing scripts, then I don't think this is the right job to start. Maybe you have smaller, not so complex feature wishes, that also benefit many others and that you can develop yourself in the GClh. That would certainly be a better start. And we can also help you if necessary and also take over the integration in the config, for example.

**Comment by janborup** [comment]
Thanks a lot both of you.

I have started the new script with require jQuery, and implemented just 2 lines.

```
$('#uxLatLon').text("Orig:"+userDefinedCoords.data.oldLatLngDisplay);
$('#viewCacheNote').css("display", "none");
```
This is allready doing half the job... 

Thanks.. I will keep on with the script.

**Comment by 2Abendsegler** [comment]
I'm going through the open issues right now. 
I added "tag: not yet in scope" to the issue.
I close the issue.
