### ISSUE TITLE
[Global] GClh does not work. 

### ISSUE THREAD

**Issue by reodor09** [2Abendsegler/GClh#1645]
GClh has stopped working. 

It is active in Tampermonkey, but does not work. And furthermore: When it is active in Tampermonkey it prevents GC Map Enhancements from working also. When GClh is deactivated, GC Map Enhancements works well. 

First this was trouble with Firefox (87.0 (64-bit)). I moved to Chrome (Ver. 89.0.4389.128). That was alright for a while, but now the same problem appears also in Chrome. 

Running on MacOS 10.15.7
Tampermonkey 4.12

I really miss my GClh!

Screenshot of map with running GClh.png…]()
Screenshot of map running with GClH deactivated.png)

**Comment by 2Abendsegler** [comment]
#1630

**Comment by 2Abendsegler** [comment]
Hi

**Comment by 2Abendsegler** [comment]
Hi,

Can you please test the new version? I ask you, because the problems are not relevant for all the user, including me.

[This is the pre-release version 0.10.17.](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true)
[This brings you back to the current version 0.10.16, if necessary.](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true)

Thanks
Frank

**Comment by reodor09** [comment]
That seems to helt! Thank you! I get this message...

![Skjermbilde 2021-04-23 kl  17 02 51](https://user-images.githubusercontent.com/10709042/115891041-eb318a80-a455-11eb-906f-36297b261ad2.png)

**Comment by 2Abendsegler** [comment]
You get this message because it is only a pre-release version. Ignore them. We will officially release version 0.10.18 next.
Thanks for your feedback .

**Comment by 2Abendsegler** [comment]
merged
