### ISSUE TITLE
[Global / Project-GC] Project-GC script does not work because of changed page header.

### ISSUE THREAD

**Issue by Vylda** [2Abendsegler/GClh#1783]
**Describe the bug**
When Global -> Header Layout -> Change header layout is unchecked (disabled), header is still modified. Some scripts not show (Project GC), Language is english.

**To Reproduce**
1. Disable Global -> Header Layout -> Change header layout
2. Disable All in Dashboard
3. Refresh page
4. Header is still modified (Project GC pane is not show)

**Expected behavior**
Header is not modified and in correct language. Other scripts has access to header

**Screenshots**
GClh disabled
![obrazek](https://user-images.githubusercontent.com/47244408/120149939-b51cbe80-c1ea-11eb-97b5-adc085811356.png)
GClh enabled
![obrazek](https://user-images.githubusercontent.com/47244408/120150017-cfef3300-c1ea-11eb-9f7d-957ee2a1ca13.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: latest

**Comment by 2Abendsegler** [comment]
Hi,

thanks for reporting.
Yes, we know this. 

Since the big changes of GS a few weeks ago, when GS installed new headers on all pages, and the GClh no longer ran, we have switched to the headers of the old GS pages. This was necessary because the new headers were now loaded asynchronously. For example, if you tap on the "play" menu, the dropdown list is only loaded at this point.

We mentioned this in our [changelog](https://github.com/2Abendsegler/GClh/blob/collector/docu/changelog.md#v01018) to Version 0.10.18.

That is the current status of our work. We don't yet know whether we can switch everything to the new headers of GS. At the moment, the other script responsibles are asked. That's stupid, we know that, but we have no other solution at the moment. For example, the owner of the "GC Tour" script has already adjusted this. Perhaps you could ask the "Project-GC" community, whether they can adapt it, that shouldn't be a big effort.

If you have no other questions to this point, please close the issue.

Sorry and best regards
Frank

**Comment by capoaira** [comment]
I will have a look into the PGC script. It is easyer to adjust this script as to rewrite all gclh header functions.
But in the long run we won't be able to avoid it ...

**Comment by capoaira** [comment]
For me the PGC part work fine:
![grafik](https://user-images.githubusercontent.com/50927164/120180105-aa265600-c20b-11eb-8cb1-378871e96005.png)

Can you please send a screenshot of your gclh settings and a screenshot of your console.

**Comment by 2Abendsegler** [comment]
@capoaira 
I also looked again at the same time.
Please deactivate everything in the config on the topic of dashboard. Then you can see it.

**Comment by capoaira** [comment]
@Vylda I'll change the PGC userscript. [Here](https://github.com/capoaira/greasemonkey-geocaching-projectgc/raw/header/greasemonkey-geocaching-projectgc.user.js) is the test version.
[Here](https://github.com/magma1447/greasemonkey-geocaching-projectgc/raw/master/greasemonkey-geocaching-projectgc.user.js) you come back to the release version.

**Comment by 2Abendsegler** [comment]
Merged with #1791
