### ISSUE TITLE
Alert...

### ISSUE THREAD

**Issue by reodor09** [2Abendsegler/GClh#1823]
In the last weeks I have got this new "banner" on the top of each cache-page:

![Skjermbilde 2021-06-21 kl  21 11 16](https://user-images.githubusercontent.com/10709042/122815045-43a9ca80-d2d5-11eb-851c-fb4933cf2c89.png)

alerts. gchl2

What is it, and do I need to take any action?

**Comment by 2Abendsegler** [comment]
Thank you for your message.

This "banner" is not of us!

Could this banner be from another script or add-on? Can you please deactivate everything else except GClh and Tampermonkey? 

I am a little at a loss.

@capoaira, @Ruko2010: Do you have an idea?

**Comment by Ruko2010** [comment]
I have no idea where this is comming from.
@reodor09 Can you right click on the Banner and hit "inspect" (on Chrome/Firefox, hope thats the right translation, I'm using the German version 😃) and send us a screenshot? Maybe the code will give us some more hints.

**Comment by reodor09** [comment]
I have found that the Norwegian script cacheturassistenten that helps with the tool cachetur.no is the suspect here. That is where the banner comes from. They even say that Gclh must be deactivated to make cahceturassistenten work. That is not going to happen…

Reodor09

**Comment by cghove** [comment]
Hi, that's a bug in the language translation matrix of the cachetur assistant. I added that banner and it's supposed to say: "You need to disable GCLH2 script to fully use the cachetur assistant" (in a couple of diferent languages).
This is due to somethings I haven't figured out in the way gclh2 have created the new headers on geocaching .com, I can't get some important bits of the cachetur assistant to work. Basicly gclh2 does something to the header so my line: "$("#cachetur-activate").click(function(e) {
        GM_setValue("cachetur_last_action", Date.now());
    }); "
Won't work, and therby making the assistant inert. I can get it to work by returning the original headers, and keeping all other functions of gclh2 active, but for the momen't I settled with an alert banner, telling users to temporary deactivate gclh2 to use the cachetur assistant. I am trying to make them compatible, but haven't figured out a solution yet.. :(

**Comment by Ruko2010** [comment]
Hi @cghove Thanks for reaching out.
Like you noticed we modified the header quite much. This was the work of @2Abendsegler. Maybe he can help you with fixing the issue in your script with the new header.

**Comment by capoaira** [comment]
Link to the cachetur script: https://cachetur.no/makro/1

It looks like they allways add the yellow banner if the gclh runs.

**Comment by cghove** [comment]
Yes for the moment the yellow banner is active if both scripts are active at the same time...
(I'm bugfixing and updating the cachetur assistant on my spare time, and the banner was the easiest temporary fix, just to avoid having lot's of questions as to why the assistant wasn't working)

**Comment by 2Abendsegler** [comment]
Hi cghove,

we have hidden the new header from GS. And we have integrated an older header from GS in English. [Here](https://github.com/2Abendsegler/GClh/blob/collector/data/header.html) you can look this older header. Basically we just changed the start tag from `nav` to `gclh_nav`. And we changed some little things in the right menue (settings ...). I don't think we changed anything else.

I can't think of any reason at the moment why your line shouldn't work. But I can't look into your script either because I don't want to log in. 

Your banner seems a little bit misleading, at first glance, but I can't take a closer look at that either.

**Comment by cghove** [comment]
Yes, I've read that.
And I know have a working beta (not released, since I'm tweaking som minor details).
Before GSP changed their headers in April?, all I had to do to have my assistant play nice with your script was to just type in ",#ctl00_uxLoginStatus_divSignedIn" behind ".user-menu" in the code below, but I actually needed to add alot of "If gclh2 / else" routines and split every thing up.
But a new version will come out accessible both through the link pasted above and here: https://github.com/cachetur-no/cachetur-assistant/ once I'm done with my latest tweaks/cleanup's... 
function ctPrependToHeader(data) {
    console.log("Injecting cachetur.no in menu");

    let header;
    if (_ctPage === "gc_map") header = $('.user-menu');
    else if (_ctPage === "gc_map_new") header = $('.user-menu');
    else if (_ctPage === "gc_bmlist") header = $('.user-menu');
    else if (_ctPage === "gc_geocache") header = $('.user-menu');
    else if (_ctPage === "gc_geotour") header = $('.user-menu');
    else if (_ctPage === "pgc_map" || _ctPage === "pgc_vgps") header = $('#pgcMainMenu ul.navbar-right');

    if (header) {
        header.prepend(data);
    }

**Comment by 2Abendsegler** [comment]
@cghove, @reodor09:
I have just installed the script for testing. 
The problem is solved and the new version is life, right?

**Comment by 2Abendsegler** [comment]
No response for more than 7 days.
I close the issue .
