### ISSUE TITLE
Cacher names with brackets will not work in VUP List

### ISSUE THREAD

**Issue by MarcusBi** [2Abendsegler/GClh#185]
The VUP List functionallity will not work correct, when a cacher on the list have brackets in the name (e.g. **Bla (Blub)**)

**Comment by 2Abendsegler** [comment]
Moin,
eine vorab Korrektur steht in folgendem Link zur Verfügung, eine neue Version gibt es erst in einigen Tagen oder so.
https://raw.githubusercontent.com/2Abendsegler/GClh/master/temp/gc_little_helper_II.user.js
LG Frank

**Comment by MarcusBi** [comment]
Auch Moin,

na du bist ja schneller als ...ich :( Der Issue stand heute auf meiner
Liste - und jetzt hast du ihn schon erledigt.
Ok, hab mir gerade mal die Änderungen angeguckt...da hätte ich länger
gebraucht ;-) Super Arbeit, vielen Dank!

LG, Marcus


2017-03-02 8:17 GMT+01:00 2Abendsegler <notifications@github.com>:

**Comment by 2Abendsegler** [comment]
Ich hab nur aus Deiner Version abgeschrieben, hihi.

**Comment by MarcusBi** [comment]
Hallo Frank,

ich habe noch ne kleine Änderung an der VUP-Liste vorgenommen. Auf welchen
Branch soll ich denn jetzt meinen Pull-Request machen?

LG, Marcus

2017-03-02 8:41 GMT+01:00 2Abendsegler <notifications@github.com>:

**Comment by 2Abendsegler** [comment]
Collector ist immer ok. Wenn wir nicht direkt in die Default Branch mergen, dann wird das nicht Deinem GitHub Konto gutgeschrieben. Also machen wir das zukünftig immer in den Collector.


Am 2. März 2017 15:34:51 MEZ, schrieb Herr Ma <notifications@github.com>:
Hallo Frank,

ich habe noch ne kleine Änderung an der VUP-Liste vorgenommen. Auf
welchen
Branch soll ich denn jetzt meinen Pull-Request machen?

LG, Marcus

2017-03-02 8:41 GMT+01:00 2Abendsegler <notifications@github.com>:

> Ich hab nur aus Deiner Version abgeschrieben, hihi.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
>
<https://github.com/2Abendsegler/GClh/issues/185#issuecomment-283579823>,

**Comment by MarcusBi** [comment]
Hallo Frank,

comitted und gepushed...

Bitte sag mir, dass alles geklappt hat (und du die Anpassung ok findest ;-)

LG, Marcus

2017-03-02 15:41 GMT+01:00 2Abendsegler <notifications@github.com>:

**Comment by MarcusBi** [comment]
Öhhhhh... den hast du doch schon gefixed

...von unterwegs gesendet

Am 03.03.2017 21:06 schrieb "2Abendsegler" <notifications@github.com>:

Assigned #185 <https://github.com/2Abendsegler/GClh/issues/185> to @MarcusBi
<https://github.com/MarcusBi>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/2Abendsegler/GClh/issues/185#event-985976828>, or mute
the thread

**Comment by 2Abendsegler** [comment]
Ja, eigentlich schon, wenn da nicht der Marcus wäre, der dort schreibt, dass er noch Änderungen an der VUP Liste vorgenommen hat. :)

Du solltest irgendetwas haben, wo Deine Änderungen hingehören, damit vor einer neuen Version überprüfbar ist, ob wir alles haben. Du kannst also dieses Issue verwenden oder ein neues aufmachen.

Im Übrigen überlassen wir es dem Antragsteller, hier also Dir, sein Issue zu schließen. :)

 

Gesendet: Freitag, 03. März 2017 um 21:10 Uhr
Von: "Herr Ma" <notifications@github.com>
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: 2Abendsegler <eifra@web.de>, Assign <assign@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Cacher names with brackets will not work in VUP List (#185)

Öhhhhh... den hast du doch schon gefixed

...von unterwegs gesendet

Am 03.03.2017 21:06 schrieb "2Abendsegler" <notifications@github.com>:

Assigned #185 <https://github.com/2Abendsegler/GClh/issues/185> to @MarcusBi
<https://github.com/MarcusBi>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/2Abendsegler/GClh/issues/185#event-985976828>, or mute
the thread

**Comment by MarcusBi** [comment]
Vom Master gefixed und von mir zur vollsten Zufriedenheit getestet...
