### ISSUE TITLE
[Browse Map] Map layer replacement doesn't work under Violentmonkey.

### ISSUE THREAD

**Issue by eddydc** [2Abendsegler/GClh#1862]
### Describe the bug

The replacement of the map layers doesn't work anymore for GClh v0.11.5.1 with Violentmonkey on FF.
The standard GC map and layers are shown on www.geocaching.com/map/default.aspx

### OS

Windows

### Browser

Firefox

### Version

0.11.5.1

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug.

You are right. Under Violentmonkey the replacement of the map layers doesn't work. So much for claiming that Tampermonkey and Violentmonkey work identically. With Tampermonkey it works. 

In addition, the GClh layers are not displayed at all, but the GC layers.

In addition, the search map button sits below the other two buttons. 

Otherwise nothing is noticeable.

**Comment by eddydc** [comment]
Hi,
Thx for the confirmation.
So what's next? Is it possible to let it work on both VM as TM? I would prefer this since TM doesn't seem to handle multiple scripts properly, whereas VM does, expect for GClH.
Many thanks in advance.
Eddy

**Comment by 2Abendsegler** [comment]
Hey Eddy,
we will fix the bug in Violentmonkey. We would also like the GClh to run with both script managers.
We're a little weak at the moment, so it will take time to fix this and the other bugs.
Cheers Frank

**Comment by eddydc** [comment]
Many thanks. Much appreciated

**Comment by eddydc** [comment]
Hi,
I tried the map out and got some odd behavior. It shows OSM for a split second and returns to the standard. The layers selection shows correctly though:
[url=https://ibb.co/wNTXqxb][img]https://i.ibb.co/kgpfTWr/2021-08-11-7-19-44.png[/img][/url]
My settings are
[url=https://ibb.co/sVYg1xb][img]https://i.ibb.co/jrX8w0b/2021-08-11-7-21-47.png[/img][/url]
Do I need to do something extra?
Cheers,
Eddy

**Comment by eddydc** [comment]
I think I've found the issue. It seems that it doesn't work when the selected default layer is the first in the list. When one doesn't choose the first one, it works perfectly
![image](https://user-images.githubusercontent.com/25877499/128981223-6bc82789-239e-4f03-b2e4-2070e223089d.png)

It could be that this issue was there in the past too, but I've been cleaning up the list and only selected the layers I really use. I needed to add a layer that comes alphabetically before OSM. 
Having said this; the sorting isn't clear to me. Despite added al last, the GC maps is listed before OSM, but Google after OSM. It isn't alphabetically to my knowledge.

**Comment by 2Abendsegler** [comment]
Moin Eddy,

you are completely right. If the first layer displayed is the default layer, it will only be displayed briefly and then switch back to the GC layer. This is a bug that probably existed from the start and has never been noticed. Well tested! 👍

And you're right about sorting too. I had asked myself this question before. 😊 It doesn't really get sorted. The layers are displayed in the order we implemented the layers. This has the advantage that new layers are always added at the bottom of the list and you don't have to change your habits for the known layers when a new layer is added. Nevertheless, I have included an alphabetical sorting as a possible feature for one of the next versions.

I'll correct the bug tonight. The fix will then be included in the next version, coming in a few days.

Now I have to go, ride my MTB and cache. 🤤

Thanks for testing.
Cheers, Frank

**Comment by 2Abendsegler** [comment]
Hey Eddy,

the bug with the first and default layer is fixed. The fix is included in the next version.

[Here is an temporary advance correction.](https://github.com/2Abendsegler/GClh/blob/bug-collector/gc_little_helper_II.user.js?raw=true) (Other changes are already included there.)
[Here you come back to the current version](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) in case the advance correction causes problems.

I have opened a new issue #1873 for an alphabetical sorting of the layers.

I will close the issue.
Cheers, Frank

---
Merged with #1872
Milestone v0.11.5.2
