### ISSUE TITLE
[Cache Listing] Hide external link warning message

### ISSUE THREAD

**Issue by eddydc** [2Abendsegler/GClh#2053]
### Is your feature request related to a problem? Please describe

Is it possible to suppress the external link warning gc.com gives each time one clicks one eg a solution checker? I've looked at the setting of GClh, but didn't see any option to do this.
![2022-02-11_7-41-38](https://user-images.githubusercontent.com/25877499/153547900-b0b7ff22-89cf-480b-b7fc-42bfdeb3c391.png)

### Describe the solution you'd like

An option to suppress the external link warning

**Comment by 2Abendsegler** [comment]
Hi, 

this external link warning is a new security feature of Groundspeak. It is already being discussed in the [Groundspeak Forum](https://forums.geocaching.com/GC/index.php?/topic/369891-html-target-attribute-broken).

It seems to be still in work at Groundspeak. We should wait a little longer before finally thinking about whether we can do something.

Perhaps there will be an option to check the popup so that you don't want to see it again in the future. And perhaps this warning will also be prevented in the future for links to GC's own pages and to pages of GC partners.

To bypass this warning, you can open the links with the right mouse button and then "Open link in new tab". 

Frank

**Comment by 2Abendsegler** [comment]
@capoaira
What do you think about the topic? Should we remove the warning messages?

It's not difficult. We have a simple [template](https://greasyfork.org/de/scripts/439287-geocaching-com-external-url-warning-remover/code) to disable the events in the cache description.

**Comment by capoaira** [comment]
It looks like GS is ready. So we can remove it.
To preserve GS security concerns, I would suggest a config parameter for it that defaults to `false`.

**Comment by capoaira** [comment]
merged with #2078
