### ISSUE TITLE
[Friends List] Friends page not working anymore

### ISSUE THREAD

**Issue by D-Jakke** [2Abendsegler/GClh#2166]
### Describe the bug

Friends page not given clicable links and (new) counts anymore.

### OS

Windows

### Browser

Opera

### GClh Version

 0.11.18

**Comment by 2Abendsegler** [comment]
Yes, you are right, some features in the Friends List no longer work due to a change on the website. We already have an [issue](https://github.com/2Abendsegler/GClh/issues/2159). capoaira and Herr-Ma have already fixed the bug. [Here](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true) you can install an advance correction. In a few days there will be a new version in which the bug has been corrected.

**Comment by 2Abendsegler** [comment]
In the new version the bug has been corrected.
I close the issue.
