### ISSUE TITLE
[LOG] Autovisit not working properly

### ISSUE THREAD

**Issue by gboye** [2Abendsegler/GClh#2241]
With the version 0.12, our TB/GC autovisit lines are set to no visit with every new log from our drafts. Is it something to do with our configuration or a bug?

**Comment by capoaira** [comment]
Thanks for reporting the problem.
For me, it works fine. Can you please attach a screenshot of the log form, which shows the issue?

**Comment by gboye** [comment]
![image](https://user-images.githubusercontent.com/8327557/197401909-1edcc8a9-819f-4e1a-9eb6-c45d2ef15f96.png)

It seems to be working properly for the first time only...

**Comment by capoaira** [comment]
Ok, which is the selected log type? It only works for Found Logs (including Attend and Webcam photo taken)
If it is one of these found log types, it is a bug. In this case, please send a screenshot of your config (Drafts and Log section) and a screenshot of your console (Press ctrl+shift+c or right click => inspect, then change to the console section)

If it is a write note, DNF, NM, NA it is the expected behavior.

**Comment by gboye** [comment]
This is from a Found Log. It works fine for the first log but starts to do this after.

![image](https://user-images.githubusercontent.com/8327557/197441172-1a414bbb-b34b-4f6f-8654-67f20017081b.png)
![image](https://user-images.githubusercontent.com/8327557/197441329-24c646e8-05fb-4fbc-84b3-294782f2e158.png)

**Comment by capoaira** [comment]
> This is from a Found Log. It works fine for the first log but starts to do this after.

Hm ok, I have at the moment no drafts to test it and I don't know when I get new... Maybe @2Abendsegler can reproduce the issue.

The console looks fine. Which Browser, OS do you use?

**Comment by gboye** [comment]
MacOS 12.6
FF 106.0.1
TamperMonkey 4.18.0

**Comment by 2Abendsegler** [comment]
@gboye
Hi,
please excuse my late answer.

I've generated some draft logs with a TB visit with your settings with no problems. So I can't reproduce the phenomenon.

I don't really have a good idea at the moment. Maybe you can try the following:

1. Please deactivate all other tampermonkey scripts and all add ons and try again.

2. Can you please test this temporary version [here](https://github.com/2Abendsegler/GClh/raw/a19271e9317d946981604a42a7bdd34bfa30a567/gc_little_helper_II.user.js). (The version is still 0.12.)

3. Could you please test the previous version [here](https://github.com/2Abendsegler/GClh/raw/9757fde829d2408265c783f98eeef670f413a707/gc_little_helper_II.user.js), because you described that you noticed the error with the current version. This may help us to limit the possible sources of error. (The version changes to 0.11.20.)

Here you come back to the current version [here](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).

**Comment by gboye** [comment]
I tried all versions and it seems to be working fine with every one. Probably a bad install in the first place. Sorry for the trouble and thanks for the help (and GClh).

**Comment by 2Abendsegler** [comment]
You are welcome.
