### ISSUE TITLE
[Pocket Query Splitter] eSwatini is not a country

### ISSUE THREAD

**Issue by novw** [2Abendsegler/GClh#2245]
![Knipsel](https://user-images.githubusercontent.com/84809678/203334615-b0d2671e-24c8-489c-a0dc-109e075949e6.JPG)

Not a clue as to what happens, but gc does not recognize Eswatini as a coutry when creating pq's? GC DOES know the country & gc-project DOES know the country.

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug.

Eswatini was officially called Swaziland until 2018. This is how it was used on the GC pages. In the meantime there was a change on the GC site to the correct name. We will also make this change with the next version.
Since there isn't much to split, there are only 51 caches, you can create the pocket query manually as a workaround.

Old:
`{"n":"Swaziland","id":"190"},`
New:
`{"n":"Eswatini","id":"190"},`

**Comment by 2Abendsegler** [comment]
The correction comes with the new version in some days. 

---
Merged with #2250
