### ISSUE TITLE
[Log Form] Submitting an image name in a new log leads to a blank page

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#2500]
### Describe the bug

Changing an image name in a new log and clicking on "Update" loads a blank page. Well, not completely blank, the header and footer is still there, but the log form is gone.

So first it's like this:

![image](https://github.com/2Abendsegler/GClh/assets/9153595/d3aa5344-c744-46d0-ab9d-1bb8f0eb326a)

and once I click the "Update" button I get this:

![image](https://github.com/2Abendsegler/GClh/assets/9153595/a0bc5d4e-7c36-4964-bb9a-dd0e52378928)

All goes well when I disable the GCLH II in the Tampermonkey.

Windows 10, Firefox 120.0

### To Reproduce

1. edit your FI draft and load at least one image into it (maybe a non-draft log will do)
2. change the image name and click the "Update button"
3. the log form goes missing

### Expected behavior

The log form is supposed to stay. :-)

### OS

Windows

### Browser

Firefox

### GClh Version

0.15

**Comment by 2Abendsegler** [comment]
I can reproduce it with a non draft log. 
We will look at it. 
Thanks for reporting the bug.

**Comment by 2Abendsegler** [comment]
Error in console:
![grafik](https://github.com/2Abendsegler/GClh/assets/22332216/2ba076d3-4a52-436b-9956-76dd65ef2fc6)

**Comment by 2Abendsegler** [comment]
The bug arises because when the image name is updated, the contents of the TBs are also refreshed. Our changes to the TBs regarding autovisit then lead to an abort. Don't ask me why it's done this way. 🙄

I have revised the autovisit feature. The bug no longer occurs and after the update the autovisit data is rebuilt.

Maybe you could test it also. I would like to release a new version this evening.
[To test please install this here.](https://github.com/2Abendsegler/GClh/raw/ab83fa4666c43fbcf2daf08012c36fb00164c667/gc_little_helper_II.user.js)
[Here you come back again.](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js)

**Comment by PontiacCZ** [comment]
You are incredibly fast. :-) I have just tested the fixed version and can confirm it works as expected. Thank you!
