### ISSUE TITLE
VIP list not rendered on a specific cache (Lesopark Dubina)

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#264]
I have just come across a weird cache - GClh II does not generate VIP list here, not even the empty one with owner name (I have "Show owner in VIP list" checked).

Check it out yourself - **Lesopark Dubina** https://coord.info/GC342ZK

![obrazek](https://cloud.githubusercontent.com/assets/9153595/24342284/464b324e-12c0-11e7-89ad-9419ab3819ec.png)

**Comment by 2Abendsegler** [comment]
You are right.

The reason is a profile link without any text. We build too the mail and message icons on this position. I think the owner want to congratulate the FTF and try to build the profile link of turistahorsky :)
![profile link without text](https://cloud.githubusercontent.com/assets/22332216/24353866/f384093e-12ef-11e7-9536-fc4bea42d884.jpg)
And this is the link: http://www.geocaching.com/profile/?guid=38ccc4fc-f2dd-4fe1-8353-b6d2a10eef95
  
Independent thereof it is a bug.

**Comment by 2Abendsegler** [comment]
The correction comes with version 0.7 in some weeks.
You can use the advance correction: https://github.com/2Abendsegler/GClh/raw/master/temp/gc_little_helper_II.user.js

Thanks for your message.
Have a nice day.

**Comment by PontiacCZ** [comment]
Thank you very much. You really don't have to be this fast. :) 

Wishing you a nice day too.

**Comment by PontiacCZ** [comment]
Verified on Lesopark Dubina, fixed.

**Comment by 2Abendsegler** [comment]
You can let your issues open, until the version is delivered, if you want. It is your issue. 
We close foreign issues only if there are no reaction of the "owner".
This only for your information. :)
