### ISSUE TITLE
[Maps] Make "Show found caches at original coordinates" button persistant

### ISSUE THREAD

**Issue by Skyhawker16** [2Abendsegler/GClh#2645]
### Is your feature request related to a problem? Please describe

The "pencil" Icon button for "Show found caches at original coordinates" appears when "View Map" is first selected from the "Play" drop-down Menu. 1) It appears to only move FOUND caches which have corrected coordinates when toggled.  2) Also, the button disappears after the  "Browse Geocaches" button is selected.

### Describe the solution you'd like

1) Make the button toggle ALL caches which have corrected coordinates, and 2) Keep the button active after "Browse Geocaches" has been selected.

**Comment by 2Abendsegler** [comment]
Hi,

the intention of this feature is to display caches at the corrected coordinates. Only caches that have been found are moved from the original to the corrected coordinates. Caches that have not been found are displayed at the corrected coordinates anyway.

If you select "View map" in the menu, you will be taken to the new map system, called "Search Map". If you select the "Browse Geocaches" button there, you will be taken to the old map system, called "Browse Map". The "Search Map" and the "Browse Map" are two completely different map systems. Unfortunately, the feature could only be implemented on the "Search Map".

**Comment by Skyhawker16** [comment]
Thank you for the explanation. Unfortunately "Browse Map" is where I would prefer it. There are several areas in the USA where there are many GeoArts. I use "Browse Map" to move around to them because they don't automatically show up on "Search Map".   After I have corrected coordinates entered, sometimes they become mixed together on the map. I would like to be able to switch between "Posted" and "Corrected" Coordinates to sort them as I work on them. My Android App (GCDroid) allows me to do this on my phone.

________________________________

**Comment by 2Abendsegler** [comment]
With apps on your phone like GCDroid or c:geo or with self-built websites like GC-Project, you have much more freedom with the features. You can do whatever you want. With the GClh we are trying to improve the existing geocaching websites. That's why we are much more limited in what is possible and what isn't.

Caches with corrected coordinates are not shown on the maps with the cache symbol, but with the symbol for corrected coordinates. In this way, you can distinguish the caches that have already been processed from the others.
![Unbenannt1](https://github.com/user-attachments/assets/1ff131e0-d48e-4a6a-95c5-bc4c041410ad)

On the "Search Map" you also have the option to filter by "solved" or "original" coordinates. This can also help to separate the caches that have already been processed from the others.
![Unbenannt2](https://github.com/user-attachments/assets/3fb91fde-f8ec-4368-9726-2bf8bed453ab)

> After I have corrected coordinates entered, sometimes they become mixed together on the map.

Do you mean that caches with corrected coordinates are displayed partly with the corrected coordinates and partly with the original coordinates? This can actually only happen within an existing browser tab. This is because map zooms are already stored in the browser memory. If you zoom in and out on the map, the display of a cache can therefore change. If you refresh the browser tab, however, the most recent data should be displayed, i.e. all caches with the corrected coordinates.

**Comment by 2Abendsegler** [comment]
I think everything was clarified here.
I'm closing the issue.
