### ISSUE TITLE
file caption missing under maximized image

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#326]
I noticed that the file caption is nowhere to be seen when watching log images in their maximized/full browser window size. The most important info about the image is usually in the caption. Descriptions are rare.

Is it possible to bring back the file caption? Ideally in bold.

Current state - the difference with CGlh II on and off in [my test WN](https://coord.info/GC28A9D):

**CGlh off (the original display mode of gc.com):**
![obrazek](https://cloud.githubusercontent.com/assets/9153595/25305099/752925e8-2775-11e7-95c2-91c33edcdabc.png)

**GClh on (file caption missing):**
![obrazek](https://cloud.githubusercontent.com/assets/9153595/25305105/969f3db6-2775-11e7-9a98-3e172b4ce01a.png)

**Comment by 2Abendsegler** [comment]
You are right, but you can see the capture on thumbnail as title if you go with the mouse over it and you can see the capture in the big one synchronous at the top or at the bottom.
![image_capture](https://cloud.githubusercontent.com/assets/22332216/25307757/03654a22-27a7-11e7-8c2d-54584ac8a02f.jpg)

**Comment by PontiacCZ** [comment]
Yes, sure, I know about that. But this issue is about the maximized "viewing mode". 

When someone attaches more images to his/her log and they are worth it, I open them to the biggest possible size for convenient viewing and browse them using left/right arrow. Typically I do this with images on events where users often write nicknames of the people to the caption. 

Like [this event](https://coord.info/GC5WPBD). If you scroll down you'll find logs with lots of images attached. And if you enter the viewing mode to better distinguish the faces, you'll at the same time lose the captions explaining what is going on in the pictures. :-)

**Comment by 2Abendsegler** [comment]
Ok, I understand.

**Comment by 2Abendsegler** [comment]
Hi,

under maximized image are now the image caption in bold, the view log button and the image description.

Like you can see in the following image, there is only the first line of image description visible. One have to scroll the browser window to see the complete image description, because the whole block under the maximized image is not relevant for calculation of the height and width of the image. This is done by fancybox, we have no influence of the calculation. We can only say, show the image a little bit smaller in generall, like groundspeak has done it. But this I don't want to do for the handful images with such a description.

I hope this is fine for you.

Best regards
Frank
PS: There is still no betaversion for your test.

![image link with caption](https://cloud.githubusercontent.com/assets/22332216/25461117/6ed21c48-2ae7-11e7-9069-f58c78787d8f.jpg)

**Comment by 2Abendsegler** [comment]
<ul>
<li>
New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/326">#326</a>] File caption missing under maximized image in cache listing:<br>
Now there are showing not only the image description under the maximized image, but the file caption and the "View Log" button too.<br>

![v0 8_screen28](https://cloud.githubusercontent.com/assets/22332216/25461583/1628eb8c-2aea-11e7-8273-c2dd72715412.jpg)

<br>
</li>
</ul>

**Comment by PontiacCZ** [comment]
That sounds perfect, looking forward to version 0.8. Thank you very much for your work! :-)

**Comment by 2Abendsegler** [comment]
(Only if you want to play with it in front of v0.8, you can now load it [here](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) as beta version. It applies to both of your issues. You can always go back with the official link for [the actual version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).)

**Comment by PontiacCZ** [comment]
Loaded the beta version and verified that both caption and description display as expected. I amended the description in my test log so it overflows to the next line - no problem with scrolling down, the entire description can be read. :) Thank you so much for your great work. Closing this ticket.
