### ISSUE TITLE
Linkliste in der Config Scrollt nicht mit nach unten

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#647]
Wenn man einen link zur Linkliste hinzufügen will, der ziemlich weit unten ist (zum Beispiel: "Watchlist"), dann wird das auf kleinen Monitoren zum Problem, da beim Drag/Drop der Bildschirm nicht nach oben scrollt.
Lösung wäre die Linkliste einfach mit-scrollen zu lassen.

**Comment by 2Abendsegler** [comment]
Man kann das aber auch mit den Pfeiltasten machen. Also mit Maus den neuen Eintrag halten und dann mit Pfeiltaste nach oben auf dem Screen nach oben rücken. Das ist auch in den linken Überschriften zur Linklist beschrieben. 
_"If you have problems to drag & drop the lower links because the Linklist area is not on the screen, then use the arrow high key on your keyboard during you hold the mouseclick."_
Könnte man auch in die FAQs mit aufnehmen.

Wenn mitgescrollt wird dann hast du womöglich Probleme einen unteren Eintrag der Linklist zu erreichen wenn die Linklist länger ist als der Bildschirm hoch ist.

**Comment by Ruko2010** [comment]
Stimmt, wer lesen kann ist klar im Vorteil 😃. Gut, dann lassen wir das so, aber in die FAQ kann es mit rein. Das übernehme ich.

**Comment by Ruko2010** [comment]
Ich habe die übrig gebliebenen Issues mal auf den nächsten Milestone verschoben.
Dann können wir jetzt eine Version fertig machen und haben für die nächste noch was zu tun. Ist ja denke ich auch viel drin. Dann kommen die Fixes auch schneller raus.
@2Abendsegler wenn du das übernehmen willst, kannst du es gern machen. Ich würde es frühestens am Mittwoch schaffen.

**Comment by 2Abendsegler** [comment]
Irgendwie hat das gerade gut gepaßt mal wieder etwas hier mitzumachen. ;)

Ich kann das heute machen. Das paßt auch gut, weil ich die aktuelle Woche noch etwas Zeit hab, falls noch was glattzubügeln ist. 

Du könntest noch das Changelog füttern, da war ja auch noch mindestens ein Punkt von dir mit dem Mehrfachlauf vom GClh, vielleicht auch noch andere Dinge. Wenn aus deiner Sicht alles fertig ist, dann gib bescheid.

Ich würde dann Changelog, die Version und die Userzähler noch anpassen und das Teil rausfeuern.

**Comment by Ruko2010** [comment]
Also vom Code her sollte das alles jetzt im Collector stehen. Am besten du gehst nochmal den Milestone durch und schaust, ob noch etwas im Changelog fehlt und ergänzt es einfach. So mache ich das auch vor einem Livegang 😃. Ich hab leider echt keine Zeit die nächsten zwei Tage um das noch zu machen, sorry.

**Comment by 2Abendsegler** [comment]
Kein Problem mach ich.
