### ISSUE TITLE
log buttons "Great story" and "Helpful" get deleted by GCLH

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#663]
**Describe the bug**
GC has just started testing a new log functionality - buttons "Great story" and "Helpful" (so far only on norwegian caches). GCLH deletes these.

**To Reproduce**
1. open this cache - https://coord.info/GC51MPR
2. scroll down the the logs section - you will be able to see the buttons mentioned above for as long as one second or not at all because GCLH removes them.
3. now disable GCLH or the entire Tampermonkey and reload the cache page. The buttons will stay visible.

**Expected behavior**
Do not delete these new buttons so the logs keep their intended look:

![obrazek](https://user-images.githubusercontent.com/9153595/40100044-d66f580a-58e2-11e8-9dab-1095c2f6d9ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 64bit
 - Browser: Firefox 
 - Version 59.0.3

**Additional context**
Tampermonkey 4.6.5757, GCLH II 0.9.6

**Comment by Ruko2010** [comment]
We'll look into this.

**Comment by Ruko2010** [comment]
I see this feature in all caches I opened in Norway, but not in other countries (i.e. Sweden, Denmark, Germany, UK).
Maybe it is really a Test that GroundSpeak is doing.

**Comment by PontiacCZ** [comment]
[Moun10Bike stated](https://forums.geocaching.com/GC/index.php?/topic/346633-introducing-log-expressions-example-included/&do=findComment&comment=5717536) "That's only being tested in Norway at this time..."

**Comment by Ruko2010** [comment]
Ok, this Issue is pretty old. I have looked at it and I see no fast way to overcome this. GC is adding the Buttons asynchronous. Since we stop loading the GC-Logs and user "GClh" Logs the button are missing.
Since this is only a test from GC, I will close it so far. I GC ever decide to implement it for all users we will have to think about a solution.

**Comment by 2Abendsegler** [comment]
Hmm ... I have a new error message to this issue.
I reopen it.

**Comment by 2Abendsegler** [comment]
Hello!

I am writing to you because you seem to be in the "inner circle" of GC little helper.

There is an update urgently needed after this update:

https://www.geocaching.com/blog/2018/05/faq-log-upvotes/

All caches in Canada and Norway have these options on geocaching.com . Here is a handy example of a Canadian cache you can look to see this feature (without helper enabled). https://coord.info/GC6W1NH 

This is a great feature but you can't use it with helper enabled.

If you have trouble understanding my email (with language barrier and all) please write back and I'll clarify.

**Comment by 2Abendsegler** [comment]
My answers:
---
Hi,

thanks for your error message.

We have been aware of the new functionality for some time now. We already have an issue for it. Sorry that we have the new functionality not yet integrated. 

Here is probably a big effort necessary because the logs are loaded and displayed by GClh. So we may have to rebuild the new functionality completely.

Honestly, no one really dared to go for it.

I'll put the issue on priority high and put your message in it. And I try to clarify how we can handle it.

Greetings
Frank
---
Here the link to the issue:
...

**Comment by 2Abendsegler** [comment]
Further mail of the cacher:

This is great to see-- I didn't know there was such an organized forum. Many of the Geocachers in my area are big fans of the helper and can't go without.

**Comment by Ruko2010** [comment]
I think this will be a hard one. Not only that we have to include the buttons, but also the sort functionality. Especially with the fact, that not all logs are loaded at startup. We should make a plan, how we handle the different states (all logs loaded, partial logs loaded, logs filtered by logtype, and some more I guess).

**Comment by Ruko2010** [comment]
2000 Meter in free Nature Camping and you are thinking about GClh, you are crazy 😉! Enjoy your trip! Think about GClh when you come back!
But you asked for it, so I give it to you. Here is the initial state loaded by GC (GClh deactivated):
![image](https://user-images.githubusercontent.com/2239440/46189990-dd451880-c2f1-11e8-98f5-e1579485f974.png)
As you can see, the default sort order is "newest", so it is sorted like today without these buttons (in fact it is a select box 😉).
Regarding your second question, yes, the sort criteria is visible in the log itself:
![image](https://user-images.githubusercontent.com/2239440/46190058-357c1a80-c2f2-11e8-94fe-5fa70641a5e9.png)

So, "all" we have to do in my opinion:

- [ ] add the buttons to our logs (maybe we can find the function the GC uses to add them, because it seams that they are "lazy loading" after the logs are loaded and use it for our logs, otherwise we must find a way to "copy" them)
- [ ] disable the event from the dropdown and add our own event.
- [ ] extract the "best story and helpful" number for all logs and add this sort criteria to all of our logs
- [ ] OnChange of the selectbox, sort our logs depending on what is selected.

If i write it down it sounds simple, but I think number 1 and 3 and 4 will be challenging.

**Comment by Ruko2010** [comment]
@2Abendsegler did you put a link to this ticket in your email response, so the guy who asked you can check the status?

**Comment by 2Abendsegler** [comment]
This sounds good!
Yes.

**Comment by Ruko2010** [comment]
I was able to add the buttons and the Events to our own logs, also while reloading more logs when scrolling down.
One Problem still exists. If a log already has an own "great story"-upvote, it will display correctly after reload, but on click, which should remove the upvote, it seams like it is adding it again and only a second click will remove the upvote.
I'll have to check this before I can continue.

**Comment by Ruko2010** [comment]
Ok, Progress. The Buttons for Great Story and Helpful are now added to our reloaded logs, even to the ones reloaded after scrolling down.
You can use this buttons like the one implemented by Groundspeak to mark a log as Helpful or GreatStory.
Last thing to do, is to implement the sorting thing.
@2Abendsegler I'm a bit helpless how to implement this. Not the technical part, but the logical.
I see some problems with reloading logs while scrolling down.

1. Case: All logs are loaded, so we have no issue with sorting
2.1. Page is a fresh load, so only some of the logs are loaden
2.2. User selects a sorting method from the dropdown. How should we continue?
2.2.1. Solution 1: Load all Logs and then sort them, Problem: with large number of logs, this can take some time
2.2.2. Solution 2: Only sort logs that are already loaded. 
Problem 1: what to do with newly loaded logs when the user scroll down. Should we "resort" everything? 
Problem 2: We only sort the loaded logs, but it could be a very usefull log (more points than all the visible logs) in the bottom, maybe right after the publish. we would only see this useful log when we reach the bottom of the logs.

I hope you understand what I mean. IMHO I think we should consider Solution 1 and load all logs and then sort them.
What do you think?

**Comment by 2Abendsegler** [comment]
I'm also for solution 1, at least that should be enough for the first time. The Sort button should then not be selectable, similar to the button "Show all logs" when pressed.

It would be even better, if you make it dependent on whether we have already loaded the logs. If we have already loaded the logs, then solution 1. If not, reload all logs in sorted order, or perhaps we let start GS with loading and showing logs like it is at the start of loading the listing. So we start new with loading.  
I'm assuming that we can also load the logs intern according to a sort.

**Comment by Ruko2010** [comment]
I will try to implement the following workflow:

1. On fresh page load, the default sort order is "newest", like we always had it in the logs. So we don't need to do anything. If the user scrolls down, thew logs are loaded in the desired order. 
2. I will remove the sort order buttons and replace them with our own buttons. (including a warning, that changing the sort order will reload all logs). (I'll post a picture of it if i'm finished, so you can have a look at it before rollout)
3. If the user chooses another sort order, we reload all logs and sort them.
4. If the user again chooses another sort order, we just have to change the sort order, because we already reloaded all logs.

I hope I can make it work that way.

**Comment by Ruko2010** [comment]
Hard thing will be appending the sort criteria to the logs (number of "great story" and "helpful" votes.

As i'm writing this. Do we need to change the sort order, if the user upvoted/downvotes a log accordingly? Or can we leave that to the next reload of the page? What do you think @2Abendsegler ?

**Comment by 2Abendsegler** [comment]
Ich gehe mal davon aus dass die Sortkriterien in den Logs enthalten sind, weil du ja in 3. die Logs sortiert.

Warum muss bei 3. der ersten Wahl eines neuen Sortkriteriums neu geladen werden und bei 4. einer weiteren neuen Wahl nicht? Wir können doch das vorhandene erstmalige Laden der Logs auch anpassen.


Nein, wir müssen die Sortierreihenfolge nicht sofort nach dem Votieren ändern. Ich glaube das wäre auch verwirrend weil das log dann plötzlich verschwinden würde und an anderer Stelle nochmal auftauchen würde.

**Comment by Ruko2010** [comment]
> Warum muss bei 3. der ersten Wahl eines neuen Sortkriteriums neu geladen werden und bei 4. einer weiteren neuen Wahl nicht? Wir können doch das vorhandene erstmalige Laden der Logs auch anpassen.

Stimmt, beim laden der Seite werden ja schon alle Logs einmal durchgeladen um die VIPs/VUPs aufzubauen, richtig? Dann müsste man "nur" für alle Logs die Sortierkriterien nachladen und an die geladenen Logs mit anhängen. Dann brauch man auch in Schritt 3 nicht alle Logs neu Laden. aber dafür muss ich schauen, ob man die Votes separat nachladen kann.

**Comment by 2Abendsegler** [comment]
Nicht nur für die VIPs... sondern auch für die Darstellung der Logs selbst. Beispielsweise Button show all logs oder die Anzeige der Logs nach logtyp (founds, DNF).

Warum müssen wir die votes separat nachladen, warum können wir das nicht direkt beim Laden erledigen. Gegebenenfalls müssen wir halt das erstmalige Laden umstellen, oder?

**Comment by Ruko2010** [comment]
Mit separat nachlade meine ich auch nur, dass die Votes nicht von anfang an in den Logs zu finden sind. Die werden erst nach und nach hinzugefügt, auch wenn die Logs dann nachgeladen werden.
Darum müsste man den Request für die Votes separat machen. Aber ja, das gleich beim Laden zu machen erscheint mir sinnvoll. Ich schau mal ob ich das umsetzen kann. Das Problem ist hier, das GS nur eine begrenzte Anzahl an Logs als Input zulässt. Das heißt, dass muss wahrscheinlich auf mehrere Requests verteilt werden.
Aber wie gesagt, ich schau es mir an.

**Comment by Ruko2010** [comment]
Again, I will tell you about my progress.
1. I added the great story / helpful count to our internal logs, that are loaded on startup, so we have this information for every log.
2. I removed the select-box that can sort logs and replaced it with our own sorting box.
3. I added a change event to the new sorting box, so when you select another sort type, I can sort the logs and display them in the right order.

Last Problem to be solved: The Buttons are not (fully) part of our new log template, so they get deleted when we sort the logs. I have to add them again after sorting.

**Comment by 2Abendsegler** [comment]
I thought the both buttons in every logs are already part of our log template. If not than we should do it. We can check whether this functionality is available before we great the log template, so it should not a problem to integrate the buttons there. 
Or is there something which goes against it?

**Comment by Ruko2010** [comment]
Oh yeah, the buttons are part of the template, but the functionality and the vote count are updated after loading the page and after the template was filled with data.
I‘m currently working on a solution toputthe data in the template and in the logs array, so we only have to load them once, but thats a bit tricky because i have no experience with jQuery template so far. But i will make it run 😉

**Comment by Ruko2010** [comment]
Ok, I think it is done, finally 😃. 
![kapture 2019-02-25 at 8 36 46](https://user-images.githubusercontent.com/2239440/53321372-9414e700-38d8-11e9-8773-7865c47debf4.gif)

@PontiacCZ since you opened this issue, can you please verify that everything is working? You have to install this branch (hope you know how to do it, if not let me know 😉). I merged the current version in it, so it should be compatible with your current configuration:
https://github.com/Ruko2010/GClh/raw/issue/663-great_story/gc_little_helper_II.user.js

@2Abendsegler If you have some spare time left, can you also do some testing?
I also created a PR, if you can like to add your comments there.

**Comment by PontiacCZ** [comment]
One thing concerns me - "All script settings will be reset!" Maybe there's something left to be set up?

![image](https://user-images.githubusercontent.com/9153595/53341869-fc7dbb80-390c-11e9-95ca-3acb6261c541.png)

**Comment by Ruko2010** [comment]
I'm pretty sure the configuration is not overwritten, but to be sure, just go to your profile (dashboard). Under your avatar you find a point "GClh Sync II". There you can manually back up your config (just save the string somewhere in a textfile):
<img width="923" alt="bildschirmfoto 2019-02-25 um 15 34 25" src="https://user-images.githubusercontent.com/2239440/53344463-06a2b880-3913-11e9-9ea1-694d62e15a27.png">

**Comment by PontiacCZ** [comment]
OK, so I'm testing it. All looks good so far. I have tried not only the norwegian cache from the OP, but also a [traditional from the Montreal center](https://www.geocaching.com/geocache/GC2XVTR) that has three times as many logs (nearly one thousand). Thanks to my add-on **gps-detect** I could see that you really load all the logs during sorting operations. :-) I understand that it is necessary.  It took about 5 seconds which is good, I think.

I have found one thing that could be confusing for users: 
1) load the Montreal cache (link above)
2) tag the second topmost log as "Helpful" (it is CanadaChris in my case)
3) now order by Most helpful - a user will expect CanadaChris to move to the top
4) not only CanadaChris does not get to the top, but it (visually) loses the Helpful tag

**Comment by Ruko2010** [comment]
Thanks for testing. The problem you describe is a known issue.
But if I'm right, when you reload the page, the helpful-vote should be there, correct?

This is because on page load, we store all informations about the votes in our own variable and reload them on sorting. The new information (if you up or downvote a log) are not transfered to our internal variable.
I'll have a second look if I can fix this.

**Comment by PontiacCZ** [comment]
Yep, after reload it's alright.

I noticed in previous posts that you store all logs to an internal array. Could you hook some onclick event to the Great story/Helpful buttons so that they transfer the new state to the array?

**Comment by Ruko2010** [comment]
That's the plan 😃.

**Comment by Ruko2010** [comment]
@PontiacCZ Just to let you know, @2Abendsegler suggested some more improvements in #991 . I'll look into this and implement them, so it will take some more time until this will be released.

**Comment by 2Abendsegler** [comment]
Hey, vielleicht irre ich mich ja, aber aus meiner Sicht hast du die wirklich schwierigen Dinge schon erledigt. Jetzt muss das nur noch rundlaufen. Wenn du möchtest kann ich unterstützen. Ich weiss noch nicht wie viel weil das Wetter gerade so geil ist, das müssen wir halt sehen. 

Schieb es gegebenenfalls in den collector. Dann kopieren wir die offenen Punkte aus dem PR in einen neuen, versehen die Punkte je mit einem weiteren Kästchen, für "in Arbeit" und dann kann ich mitarbeiten. (Nicht in ne andere branch schieben, sonst werden die commits nicht gutgeschrieben.)

**Comment by Ruko2010** [comment]
Ist schon ok, ich schau es mir an. Ich muss nur den ganzen Ablauf nochmal überblicken und ggf. umstrukturieren. Denn es muss dann ja entweder vor dem ersetzen der Logs die Votes geladen werden, oder man macht es dann im nach hinein. Aber wie gesagt, dass muss ich mir alles nochmal durchdenken und ein paar Stunden Zeit nehmen dafür.
Diese Woche ist dafür leider schlecht, denn es stehen viele private Termine an und das Wochenende ist fürs Campen reserviert 😉. Darum schrieb ich, dass es noch etwas dauern wird.
Ich muss mir auch den Prozess nochmal genau anschauen, wie die Logs eigentlich geladen werden.

Wenn ich es richtig sehe macht es so am meisten Sinn:
1. Alle Logs von GS löschen
2. Button für das Sortieren der Logs deaktivieren
3. Anfangen die Logs zu laden. Sobald X logs geladen sind, diese anzeigen (mit Anzeige der Vote buttons, aber ohne die "Anzahl" der Votes und ohne die Buttonfunktion)
4. Wenn X Logs gesammelt wurden, Votes nachladen und die schon angezeigte Logs anpassen.
5. Wenn Y Logs angezeigt wurden, stoppen mit anhängen der Logs (nachladen läuft aber intern weiter)
6. Wenn alle Logs geladen sind, Sortierung wieder aktivieren.

**Comment by PontiacCZ** [comment]
Just wanted to let you know about a small glitch I've run into with this modified version: when I visit some cache pages (like https://coord.info/GC83QP8), the GClh II generates the "Great story" and "Helpful" buttons eventhough this functionality is not yet enabled for the Czech republic.
![image](https://user-images.githubusercontent.com/9153595/53556748-c75bae00-3b44-11e9-9e10-31a780249389.png)

After F5 (reload) they disappear.

I go back to my dashboard and then again to this cache page - they're there again.

**Comment by Ruko2010** [comment]
Thanks for reporting, I'll fix this with the other implementations.

**Comment by Ruko2010** [comment]
@PontiacCZ Sorry for letting this thing laying around so long. But i'm now back on it.
> I have found one thing that could be confusing for users:
> 
> 1. load the Montreal cache (link above)
> 2. tag the second topmost log as "Helpful" (it is CanadaChris in my case)
> 3. now order by Most helpful - a user will expect CanadaChris to move to the top
> 4. not only CanadaChris does not get to the top, but it (visually) loses the Helpful tag

This Problem is now fixed.
In my opinion, there are some things left to do:

- [ ] Check if Upvote Button are only on pages (Countrys), that have this feature originally from Groundspeak (Norway, Canada, ...)
- [ ] on first page load: Upvote Buttons appear, disappear and appear again.
- [ ] Do not load (show!) all logs while sorting the logs. Only show a certain number (initial log size?) or as many logs as have been displayed before.


@PontiacCZ if you want to test the current version again, please install it from here:
https://github.com/Ruko2010/GClh/raw/issue/663-great_story/gc_little_helper_II.user.js

I'll update the Ticket if I have implemented the left 3 Points.

**Comment by Ruko2010** [comment]
Ok, all things have been implemented. While sorting the logs, we now only display as many logs as currently shown, not all. So this should be a lot faster.

One (little) issue is still left. The buttons do not disappear any more, but the votecount does. Here is a image that shows that:
![Kapture 2019-05-15 at 21 40 34](https://user-images.githubusercontent.com/2239440/57804071-1c798a00-775a-11e9-9d75-9194cb625013.gif)
I'm not sure if I can fix this 😔.

@PontiacCZ I would appreciate it if you could test the new version. You can install it via this link:
https://github.com/Ruko2010/GClh/raw/issue/663-great_story/gc_little_helper_II.user.js

@2Abendsegler are you able to test the feature? Or are you still on holiday?

**Comment by PontiacCZ** [comment]
Since GS don't seem to rush with spreading the log upvote functionality, we don't have to hurry as well on this one. Probably. ;-) But anyway, thank you, Ruko2010, for your incredible work. I checked it out:

- "Check if Upvote Button are only on pages (Countrys), that have this feature originally from Groundspeak (Norway, Canada, ...)": I checked canadian and norwegian caches, the upvote buttons display there just fine. They no longer display on czech caches so I consider this solved. :-)

- "on first page load: Upvote Buttons appear, disappear and appear again.": they're stable now, at least here on my FF 66.0.5.  But you're right, the votecount disappears for a moment (so do users' avatar pictures). But I wouldn't call that an issue. :-)


I've discovered another issue, it's sort of **upvote persistance**.
1) open [Le Suppositoire Inn de Montréal](https://coord.info/GC2XVTR)
2) tag the most recent log as "Helpful" (in my case it is sexyboo's DNF) and untag it right away (clear the Helpful flag) so it looks as before. 
3) change the sorting mode to the "Most helpful". Voila, sexyboo's log is helpful again! (while it actually is not, it is just somehow stuck in the GClh memory)

**Comment by Ruko2010** [comment]
> I've discovered another issue, it's sort of **upvote persistance**.

Thanks for testing. This was a little copy-paste error (shame on me 😃). This is fixed now.

**Comment by Ruko2010** [comment]
omg. I just realized, this Ticket is exactly 1 Year old 😱

**Comment by PontiacCZ** [comment]
Yup, really. :-D

I updated the script and verify that the "upvote persistance" is fixed.

**Comment by Ruko2010** [comment]
Ok, nice to hear. I‘ll wait for 2Abendseglers feedback and will then publish a new version along this/next week.

**Comment by Ruko2010** [comment]
Will be deployed in the next Version
