### ISSUE TITLE
Small Map in Cache Listing shows Error

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#787]
**Describe the bug**
There is a small yellow error in the top right of the map on the Listing Page. Maybe this is due to the licence change on google maps?

**Screenshots**
![image](https://user-images.githubusercontent.com/2239440/44585063-4abdd080-a7ab-11e8-8ce2-9d4db2c4d700.png)

**Comment by CachingFoX** [comment]
# Analysis
GClh calls following url 
`https://maps.google.com/maps/api/staticmap?zoom=11&size=248x248&maptype=roadmap&markers=icon:http://www.geocaching.com/images/wpttypes/pins/.png|48.13595,11.57055`

Google gives following answer
`x-staticmap-api-warning: Failed to fetch image url http://www.geocaching.com/images/wpttypes/pins/.png
`

[Google Static Maps / Error messages](https://developers.google.com/maps/documentation/maps-static/error-messages#warnings)

##Reason
The url to the marker icons in incorrect, because GClh can not detect the cache type. Googles includes the default pin

**Comment by CachingFoX** [comment]
# Solution
Use `unsafeWindow.mapLatLng` to get cache type and coordinates. These makes the code much simpler. The mapLatLng structure handles original and user defined coordinates.
