### ISSUE TITLE
Edit and Image Links to own caches doesn't shown

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#810]
**Describe the bug**
Edit and Image Links to own caches doesn't shown
Error message: *Edit and Image Links to own caches in profile:: links[i].parentNode is null*

**To Reproduce**
- Log into www.geocaching.com
- Open the new dashboard
- Goto Hides: [https://www.geocaching.com/my/owned.aspx ](https://www.geocaching.com/my/owned.aspx)
- See web console

**Screenshot**
![grafik](https://user-images.githubusercontent.com/1838534/44863963-d5f10780-ac7e-11e8-8b7b-9fe342a2173a.png)

**Expected behavior**
Have the edit and image link to my own caches.

**Desktop (please complete the following information):**
* Windows 7 64-bit
* Firefox 61.0.2
* Tampermonkey v4.7.5788
* GClh 0.9.11

**Additional context**
Reason unknown

**Comment by Ruko2010** [comment]
This is the original code. Somehow, after the fist link (edit Cache) is added to the parent node, the reference for the parent node goes missing (maybe because the code of the parent node changes?). 
I'm not sure, why the Link addition is separated, because the If statement before the secound link is the same as in the first line, so it is always true. Maybe before there were another condition around it, but at this time, the if is always true, can be removed and both links can be added at once, and this fixes the bug.
![image](https://user-images.githubusercontent.com/2239440/45866307-a1093980-bd80-11e8-861c-96e93dd2da24.png)
