### ISSUE TITLE
Display difficulty/terrain in bookmark lists.

### ISSUE THREAD

**Issue by anvanlaer** [2Abendsegler/GClh#975]
Is there a way to display the difficulty/terrain in a list?

**Comment by 2Abendsegler** [comment]
In which list? 
Perhaps you have a little bit more information?

**Comment by anvanlaer** [comment]
My apoligies, i mean a bookmark list of caches.

**Comment by 2Abendsegler** [comment]
Ok, I understand.
Do you know pocket queries? You can create a pocket query from every bookmark list. And a pocket query includes the information difficulty and terrain. Do you know it?

**Comment by anvanlaer** [comment]
I use pq alot. But for some lists, per example, a list of mysteries i am solving, it would be handy if that info is also displayed in the list.

**Comment by 2Abendsegler** [comment]
Please excuse my unceasing questions, of course your feature request is possible. But I still can not really see why the info is necessary in bookmark lists if we have it in the pocket queries. What prevents you from watching your solved mysteries in the pocket query?

**Comment by 2Abendsegler** [comment]
@Ruko2010 
I have to admit that I could have used difficulty and terrain already in bookmark lists. I'm just worried that more "missing" data will be requested in bookmark lists soon, and the bookmark lists will eventually look like pocket queries. I'm not quite sure what we should do. What do you think?

If we realize it then I would like to integrate it into the determination of the corrected coordinates, so that we do not have to read the cache listings several times, once for this and once for the other.

**Comment by 2Abendsegler** [comment]
- [ ] Note that GC Tour works.

**Comment by Ruko2010** [comment]
I think if we integrate it with the functionality of fetching corrected Coordinates it will be ok. We could rename the button to "fetch additional information" or something and use the same table column to display the infos.
This also should not be to much effort, because all the basic functionality is already there.
If your ok with it, I'd like to implement it.

**Comment by Ruko2010** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2239440/52464561-a1fa0680-2b7b-11e9-919d-edaadb3f40dc.gif)

**Comment by anvanlaer** [comment]
Great!   When will the next update be?

**Comment by 2Abendsegler** [comment]
@anvanlaer 
In a few days, Ruko2010 works hard.

@Ruko2010 
Looks great.

**Comment by anvanlaer** [comment]
Great!
